apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    creationTimestamp: "2022-01-17T13:39:59Z"
    generation: 1
    managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:clusterResourceWhitelist: {}
          f:destinations: {}
          f:sourceRepos: {}
        f:status: {}
      manager: argocd-server
      operation: Update
      time: "2022-01-17T13:39:59Z"
    name: default
    namespace: argocd
    resourceVersion: "955910"
    selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/default
    uid: ad917bdb-550b-4ee8-a75c-947612308638
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    sourceRepos:
    - '*'
  status: {}
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"AppProject","metadata":{"annotations":{},"name":"do380","namespace":"argocd"},"spec":{"destinations":[{"namespace":"*","server":"*"}],"sourceRepos":["*"]}}
    creationTimestamp: "2022-01-17T13:45:13Z"
    generation: 5
    managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2022-01-17T13:58:45Z"
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:clusterResourceWhitelist: {}
          f:destinations: {}
          f:namespaceResourceWhitelist: {}
          f:sourceRepos: {}
        f:status: {}
      manager: argocd-server
      operation: Update
      time: "2022-01-17T14:01:41Z"
    name: do380
    namespace: argocd
    resourceVersion: "965648"
    selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/do380
    uid: 86206d68-9a96-4045-8db0-f7648f88e0d6
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
    sourceRepos:
    - '*'
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
