apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
 name: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
spec:
  channel: alpha
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: argocd
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: argocd-operator.v0.1.0
